default: &default
  otp_url: 'https://ac.khoslalabs.com/hackgate/hackathon/otp'
  basic_details_url: 'https://ac.khoslalabs.com/hackgate/hackathon/kyc/raw'
  send_sms: true
  from_phone_no: 8067683816
  remote_url : 'http://localhost:9090'
  citrus_access_key: EUAJ540TBB3BP08X9SX0
  payment_return_url: '/api/v1/transactions/update_txn' 
  kyc_errors: { K-100: "Resident authentication failed",
                K-200: "Resident data currently not available",
                K-540: "Invalid KYC XML",
                K-541: "Invalid e-KYC API version",
                K-542: "Invalid resident consent ('rc' attribute in 'Kyc' element)",
                K-543: "Invalid timestamp ('ts' attribute in 'Kyc' element)",
                K-544: "Invalid resident auth type ('ra' attribute in 'Kyc' element does not match what is in PID block)",
                K-545: "Resident has opted-out of this service",
                K-550: "Invalid Uses Attribute",
                K-551: "Invalid 'Txn' namespace",
                K-552: "Invalid License key",
                K-569: "Digital signature verification failed for e-KYC XML",
                K-570: "Invalid key info in digital signature for e-KYC XML (it is either expired, or does not belong to the AUA or is not created by a well-known Certification Authority)",
                K-600: "AUA is invalid or not an authorized KUA",
                K-601: "ASA is invalid or not an authorized KSA",
                K-602: "KUA encryption key not available",
                K-603: "KSA encryption key not available",
                K-604: "KSA Signature not allowed",
                K-605: "Neither KUA key nor KSA encryption key are available",
                K-955: "Technical Failure",
                K-999: "Unknown error"}

development:
  <<: *default
  neat_setting: 800
  site_url: 'http://example.com:3000'

test:
  <<: *default
  site_url: 'http://example.com:3000'

production:
  <<: *default
  site_url: 'http://example.com:3000'
