development:
  adapter: oracle_enhanced
  database: XE
  username: refund_app
  password: refund_app

test:
  adapter: oracle_enhanced
  database: XE
  username: refund_app_test
  password: refund_app_test